services:
  postgres-booking:
    image: postgres
    container_name: postgres-booking
    environment:
      POSTGRES_DB: booking_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"
    restart: always

  postgres-user:
    image: postgres
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  service-registry:
    build:
      context: ./service-registry
    container_name: service-registry
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8761 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
    depends_on:
      service-registry:
        condition: service_healthy

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
        config-server:
          condition: service_healthy

  booking-service:
    build:
      context: ./booking-service
    container_name: booking-service
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
      config-server:
        condition: service_healthy
      postgres-booking:
        condition: service_started

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
      config-server:
        condition: service_healthy
      postgres-user:
        condition: service_started