services:
  postgres-booking:
    image: postgres
    container_name: postgres-booking
    environment:
      POSTGRES_DB: booking_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    restart: always

  postgres-user:
    image: postgres
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  service-registry:
    image: microservices/service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  config-server:
    image: microservices/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
    depends_on:
      - service-registry

  api-gateway:
    image: microservices/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - config-server
      - service-registry

  booking-service:
    image: microservices/booking-service
    container_name: booking-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - config-server
      - service-registry
      - postgres-booking

  user-service:
    image: microservices/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - config-server
      - service-registry
      - postgres-user