spring:
  application:
    name: api-gateway

  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8888}

  cloud:
    openfeign:
      lazy-attributes-resolution: true
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 8000
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.retry: DEBUG
    org.springframework.boot.context.config: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
