spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay #Fångar inkommande JWT och bifogar den i Authorization headern till separata tjänsten (booking-service)
      routes:
        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs/**, /user-service/v3/api-docs
          filters:
            - RewritePath=/user-service(?<segment>.*), $\{segment}

        - id: booking-service-swagger
          uri: lb://booking-service
          predicates:
            - Path=/booking-service/v3/api-docs/**, /booking-service/v3/api-docs
          filters:
            - RewritePath=/booking-service(?<segment>.*), $\{segment}

        - id: user-service-api
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: booking-service-api
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: secret-key-here

# Eureka uppkoppling
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #Adress till service reg

# Aggregerar Swagger UI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Booking Service
        url: /booking-service/v3/api-docs

server:
  port: 8080 # Port för Gateway

management:
  endpoints:
    web:
      exposure:
        include: "gateway"

logging:
  level:
    org.springframework.cloud.gateway: TRACE