spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri: http://[auth-server-url]/.well-known/jwks.json
  application:
    name: user-service

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 8000
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.retry: DEBUG
    org.springframework.boot.context.config: DEBUG

# Swagger ui -_- user-service
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha