server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: booking-service
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/bookings/**
              filters:
                - GatewayAuthFilter

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
              filters:
                - GatewayAuthFilter

            - id: service-registry
              uri: lb://eureka:password
              predicates:
                - Path=/eureka/**
              filters:
                - GatewayAuthFilter
eureka:
  client:
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/
app:
  eureka-server: localhost