server:
  port: 8085

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://postgres-booking:5431/booking_service
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password
eureka:
  client:
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
app:
  eureka-server: localhost
