eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://postgres-booking:5431/booking_service
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password